language: node_js
node_js:
- "node"
cache: npm
script: now --token $NOW_TOKEN
after_script: now alias --token=$NOW_TOKEN
env:
  global:
    secure: YnRpeeKwwr4ulG+KV/dsRqVKbhJZ1c52KrIoog0mBxANdvP7JNrECGigN0A96xBr1BhTMmG3GpjzZvcVhbYQXdHrbnkI13FlvPyYGjxk6pDrvZkitqMe/0Kx4BcuXT0ioDxTiZD5q3lw55gM+n017Nw+Hqv3aQMjXsZVnv07Lfu4QTa9wugTn4terogFqwtlKYG891s9SJeLQXf7rMHngkHzV6yOFJouyFfg8aVba/vgYnKTyT9l71vDgIUTGk05134pFxG5zJvV7K1Lk7nN9/DhQOHYNscQz29mIgyawBbirhVfrpIX/8swLU0lkT+K1XSqUUN+sJTCTU7e6luT2z7WoHRiralkIlUe1EjX9eb5tHnoQtRzdqIX/xlOi+FnQ3tnQ46+g1wbsGefCtsVY+Uqs8Zb+H7DMBYkgxy1YlbgtbY9sumpogyDtDPup6ag0Z+6PF7gSrwpDm1/B/YaMBhrCCEyTZwich7ODVCK6dXsWWskNwjKraF1zvs+We/KL9N29nuNLDREuGBk13dva1X8SXSMPctN9gmYokfMJgzqRkjga6J0tb3E9ArvK0FzzE0/H1yjojfpgXok4Ab8EZpBXZyVFtks8mkERO2uZwz42By41HKRzMHOLTco1GKlt3HPMK3qD6vxrnQgzNfFw1nEwiG6ZYeLjRg2NTsa/vQ=
