language: python
python:
- "3.6"
branches:
  only:
    - master
before_script:
- pip install csvs-to-sqlite
- pip install Markdown==2.6.11
- pip install https://github.com/simonw/datasette/archive/master.zip
- npm install -g heroku
- heroku plugins:install heroku-builds
- curl -L -o data.zip https://github.com/fivethirtyeight/data/archive/master.zip
- unzip data.zip
- python make_metadata.py
- csvs-to-sqlite data-master fivethirtyeight.db
script:
- export LATEST_DATASETTE=`curl -s "https://api.github.com/repos/simonw/datasette/commits/master" | jq -r .sha`
- datasette publish heroku fivethirtyeight.db
  -m metadata.json
  -n fivethirtyeight-datasette
  --install=datasette-vega
  --install=datasette-jellyfish
  --install=datasette-copyable>=0.2
  --version-note=$LATEST_DATASETTE
  --branch=$LATEST_DATASETTE
