language: node_js
node_js:
- "node"
cache: npm
branches:
  only:
    - master
before_script:
  - curl -o data.zip https://github.com/fivethirtyeight/data/archive/master.zip
  - curl -o datasette.zip https://github.com/simonw/datasette/archive/master.zip
  - npm install -g now
script: now --token=$NOW_TOKEN --force
after_script: now alias --token=$NOW_TOKEN
